org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configureondemand=true
org.gradle.configuration-cache=true
org.gradle.workers.max=10
org.gradle.warning.mode=summary
org.gradle.jvmargs=-Xmx8g -XX:+UseG1GC -XX:MaxMetaspaceSize=2g -Dfile.encoding=UTF-8
org.gradle.tooling.parallel=true

kotlin.code.style=official
kotlin.daemon.jvmargs=-Xmx8g -XX:+UseG1GC -XX:+UseStringDeduplication
kotlin.native.ignoreDisabledTargets=true
kotlin.mpp.enableCInteropCommonization=true

android.useAndroidX=true
android.nonTransitiveRClass=true
